### ISSUE TITLE
Question about icons on the menu bar of file explorer

### ISSUE THREAD

**Issue by Dhyfer1** [fayazara/fluenticons#5]
Hi. I need your help. I want to customize the toolbar of an app to zip/unzip files by replacing its icons with the icons shown in the image. What I want to know is, in which dll or exe file or in which directory could I find the icons in two colors shown in the image?

![0xAeu.png](https://user-images.githubusercontent.com/50301201/146962382-bdd060c2-9b5a-49d9-ae7c-2d42a6ea861c.png)

Thanks.

**Comment by fayazara** [comment]
Hey @Dhyfer1 looks like these are custom color changed icons, which unfortunately is not possible in my site fluenticons.co. I think these are called monotone and you could use a svg editing tool like figma to do this.

**Comment by Dhyfer1** [comment]
> Hey @Dhyfer1 looks like these are custom color changed icons, which unfortunately is not possible in my site fluenticons.co. I think these are called monotone and you could use a svg editing tool like figma to do this.

Uh. It's okay. Hey, could you add an option on your site to export the icon as a bmp file with transparency? As I said before, I want to customize the taskbar of a program that I use daily by replacing its icons with those of Windows 11. The icons on the toolbar for the app that I want to customize are images in bmp format with transparency, and the icon that the app uses in the context menu of the file explorer is also a bmp file with transparency. 

Do you have any idea how to create a bmp file with transparency?

**Comment by cfpwastaken** [comment]
In most of the SVGs that get downloaded, there are actually 2 paths which can have a different color.
If you edit that manually (there will be 2 fill attributes), it can look like this.
![image](https://user-images.githubusercontent.com/44261356/220999549-f91fbf6d-31e5-4f24-b7bf-6ec167a1ff34.png)
