### ISSUE TITLE
Can you add Japanese version of text icon?

### ISSUE THREAD

**Issue by hatopoppoOfficial** [fayazara/fluenticons#6]
Can you add Japanese version of text icon such an "Zi" or "Ga"?
We want use the Japanese version of the text icons.

**Comment by fayazara** [comment]
Hey @hatopoppoOfficial, are you seeing anything missing from, the microsoft icon directory that is not here?

**Comment by hatopoppoOfficial** [comment]
I'm so sorry, I was mistaken.
