### ISSUE TITLE
win11 styled scrollbars

### ISSUE THREAD

**Issue by yashash1511** [fayazara/fluenticons#7]
![image](https://user-images.githubusercontent.com/89068816/153697128-53908246-6ee3-430c-b389-84b6a915bb98.png)
![image](https://user-images.githubusercontent.com/89068816/153697768-307119b3-65c5-4c11-b1e5-3dba00032c26.png)

can I update the scrollbar design to look like  win11 :)

**Comment by fayazara** [comment]
Hey @yashash1511 this change feels unnecessary for now. 

Please let me know if you would like to contribute on any other feature, I would love to help you it.

**Comment by yashash1511** [comment]
> Hey @yashash1511 this change feels unnecessary for now.

okey :)
